version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  cloudfoundry: circleci/cloudfoundry@0.1.73

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore                                 

      - run:
          name: "Build Application"
          command: dotnet build

  hold:
    executor:
      name: windows/default
    steps:
      - run:
          name: "Wait for approval"
          command: echo Wait
workflows:
  build-deploy-sandbox:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - cloudfoundry/push:
          filters:
            branches:
              only:
                - main
          appname: eligibility-checker-sandbox
          requires: 
            - build
          org: nicts-probate
          endpoint: https://api.london.cloud.service.gov.uk
          space: sandbox
          context: govuk-paas-sandbox
          manifest: manifest.yml